OTA-861: inhibit the 2nd minor version upgrade
openshift/cluster-version-operator pull request #1079
Opened 2024-08-20 21:35 UTC by hongkailiu

2024-08-21 00:45 UTC, hongkailiu commented
/test e2e-aws-ovn-techpreview

2024-08-21 09:27 UTC, hongkailiu commented
/test e2e-aws-ovn-techpreview

2024-08-21 16:23 UTC, Davoska commented
Hello @hongkailiu :wave:
The pull request contains two commits that have an identical message:
```shell
c9852051 (HEAD -> OTA-861) inhibit the 2nd minor version upgrade
08ece187 inhibit the 2nd minor version upgrade
```

Could you please update the commits and provide some additional information in them as well? The additional information would be greatly appreciated :raised_hands:

2024-08-22 13:25 UTC, petr-muller commented
I'll sit this one out and leave it for David to review :wink:

2024-08-22 14:32 UTC, Davoska commented
Petr, back to status API!

2024-08-26 15:21 UTC, Davoska requested changes
I would like to discuss the wording of the precondition check :raised_hands: 

Other than that, the PR seems to be good to merge.

2024-08-26 16:32 UTC, Davoska commented
tldr; everything seems to be working as expected :raised_hands:
---

I wanted to learn something new by testing this PR. I have created three dummy releases. All these releases contain this PR and only differ in their version. I had to force the upgrades, as the releases were not signed. 

Upgrade from `4.17.0-0.ci.test-2024-08-26-132104-ci-ln-c7kz9p2-latest` to `4.18.98`:

```
$ oc adm upgrade --to-image quay.io/dhurta/ocp-release@sha256:bdb2e638b14cb5bfbc1e1502b983210dce43e6258827cedf65311391bc133065 --allow-explicit-upgrade --force --allow-upgrade-with-warnings 
warning: The requested upgrade image is not one of the available updates. You have used --allow-explicit-upgrade for the update to proceed anyway
warning: --force overrides cluster verification of your supplied release image and waives any update precondition failures.
Requested update to release image quay.io/dhurta/ocp-release@sha256:bdb2e638b14cb5bfbc1e1502b983210dce43e6258827cedf65311391bc133065
```

Checking events:

```
$ oc events -n openshift-cluster-version
...
4m39s                   Warning   PreconditionWarn      ClusterVersion/version                           precondition warning for payload loaded version="4.18.98" image="quay.io/dhurta/ocp-release@sha256:bdb2e638b14cb5bfbc1e1502b983210dce43e6258827cedf65311391bc133065": Precondition "ClusterVersionRecommendedUpdate" failed because of "NoChannel": Configured channel is unset, so the recommended status of updating from 4.17.0-0.ci.test-2024-08-26-150237-ci-ln-dxk8yqk-latest to 4.18.98 is unknown.
```

Only `ClusterVersionRecommendedUpdate` precondition check warning as expected.

---

Upgrade from `4.18.98` to `4.18.99`:

```
$ oc adm upgrade --to-image quay.io/dhurta/ocp-release@sha256:a570a6a0957729b3f876750f774c9bb2411fd3596093b587f2de998604cdd5ee --allow-explicit-upgrade --force --allow-upgrade-with-warnings 
warning: The requested upgrade image is not one of the available updates. You have used --allow-explicit-upgrade for the update to proceed anyway
warning: --force overrides cluster verification of your supplied release image and waives any update precondition failures.
warning: --allow-upgrade-with-warnings is bypassing: the cluster is already upgrading:

  Reason: ClusterOperatorsUpdating
  Message: Working towards 4.18.98: 110 of 900 done (12% complete), waiting on etcd, kube-apiserver
Requested update to release image quay.io/dhurta/ocp-release@sha256:a570a6a0957729b3f876750f774c9bb2411fd3596093b587f2de998604cdd5ee
```

Checking events:

```
$ oc events -n openshift-cluster-version
...
3m9s                    Warning   PreconditionWarn      ClusterVersion/version                           precondition warning for payload loaded version="4.18.99" image="quay.io/dhurta/ocp-release@sha256:a570a6a0957729b3f876750f774c9bb2411fd3596093b587f2de998604cdd5ee": Precondition "ClusterVersionRecommendedUpdate" failed because of "NoChannel": Configured channel is unset, so the recommended status of updating from 4.18.98 to 4.18.99 is unknown.
```

The new precondition check does not fail when redirecting a partial minor upgrade to a newer patch version in the same minor version.

---

Upgrade from `4.18.99` to `4.19.99`:

```
$ oc adm upgrade --to-image quay.io/dhurta/ocp-release@sha256:88a0a7c9e196b7df971c50856f5024891c8ecb2ce61a84220e2b193c3ced33f3 --allow-explicit-upgrade --force --allow-upgrade-with-warnings 
warning: The requested upgrade image is not one of the available updates. You have used --allow-explicit-upgrade for the update to proceed anyway
warning: --force overrides cluster verification of your supplied release image and waives any update precondition failures.
warning: --allow-upgrade-with-warnings is bypassing: the cluster is already upgrading:

  Reason: ClusterOperatorsUpdating
  Message: Working towards 4.18.99: 110 of 900 done (12% complete), waiting on etcd, kube-apiserver
Requested update to release image quay.io/dhurta/ocp-release@sha256:88a0a7c9e196b7df971c50856f5024891c8ecb2ce61a84220e2b193c3ced33f3
```

Checking events:

```
$ oc events -n openshift-cluster-version
...
83s                     Warning   PreconditionWarn      ClusterVersion/version                           precondition warning for payload loaded version="4.19.99" image="quay.io/dhurta/ocp-release@sha256:88a0a7c9e196b7df971c50856f5024891c8ecb2ce61a84220e2b193c3ced33f3": Forced through blocking failures: Multiple precondition checks failed:
* Precondition "ClusterVersionUpgradeable" failed because of "MinorVersionClusterUpgradeInProgress": The minor level upgrade to 4.19.99 is not allowed while there is already a minor level upgrade from 4.17.0-0.ci.test-2024-08-26-150237-ci-ln-dxk8yqk-latest to 4.18.99 in progress. Please wait until the existing minor level upgrade completes.
* Precondition "ClusterVersionRecommendedUpdate" failed because of "NoChannel": Configured channel is unset, so the recommended status of updating from 4.18.99 to 4.19.99 is unknown.
```

The precondition check `ClusterVersionUpgradeable` fails as expected because of the `MinorVersionClusterUpgradeInProgress` check.

2024-08-27 16:30 UTC, hongkailiu commented
> I have created three dummy releases. All these releases contain this PR and only differ in their version.

2024-08-27 19:58 UTC, hongkailiu commented
/retest-required

2024-08-27 20:01 UTC, hongkailiu commented
Thanks for the cmds creating a release with PR.
I will ask the testing strategy in our team channel.

2024-08-29 00:22 UTC, hongkailiu commented
/hold

https://github.com/openshift/cluster-version-operator/pull/1080

2024-08-30 19:57 UTC, hongkailiu commented
/close

2024-08-30 19:57 UTC, closed without merging