Bug 1927168: pkg/payload/task: Fail fast for UpdateError
openshift/cluster-version-operator pull request #573
Opened 2021-05-24 23:44 UTC by wking

Things like API-server connection errors and patch conflicts deserve some retries before we bubble them up into ClusterVersion conditions.  But when we are able to retrieve in-cluster objects and determine that they are not happy, we should exit more quickly so we can complain about the resource state and start in on the next sync cycle.  For example, see the recent e02d1489a5 (#560) and the older cc9292a061 (#400).  This commit uses the presence of an UpdateError as a marker for "fail fast; no need to retry".

The install-time backoff is from fee2d06871 (#136).  I'm not sure if it really wants the same cap as reconcile and update modes, but I've left them the same for now, and future commits to pivot the backoff settings can focus on motivating those pivots.

2021-05-26 19:36 UTC, jottofar commented
/lgtm

2021-05-27 04:36 UTC, wking commented
/hold

while I work out what is going wrong with the [unit][1] and [e2e-operator][2] jobs.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/573/pull-ci-openshift-cluster-version-operator-master-unit/1397771303145967616
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/573/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-operator/1397751412221284352

2021-07-23 09:29 UTC, vrutkovs commented
/retest

2021-07-23 09:52 UTC, vrutkovs requested changes
/lgtm cancel

Not sure why unit/e2e tests are failing. Changing `wait.Backoff.Steps` to 2 in `setupCVOTest` fixes one unit tests, but I don't think its a good idea

2022-02-03 10:48 UTC, closed without merging

2022-08-05 17:15 UTC, wking commented
Ended up landing via #577.