Bug 2028602: lib/resourcemerge/apps: Default Deployment replicas to one
openshift/cluster-version-operator pull request #702
Opened 2021-12-02 18:22 UTC by wking

Picking #698 back to 4.9, but without `pointer.Int32`, which [isn't part of 4.9's vendored `pointer` package][1].

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/700/pull-ci-openshift-cluster-version-operator-release-4.9-golangci-lint/1466469531768590336#1:build-log.txt%3A16

2021-12-03 09:51 UTC, vrutkovs approved these changes
/lgtm

2021-12-03 09:54 UTC, vrutkovs requested changes
/lgtm cancel

`gofmt` is not happy about int32Pointer

2021-12-06 22:18 UTC, wking commented
16661bef -> d0f6f7ba should fix the gofmt issue.  And the 4.10 bug was verified, so:

/bugzilla refresh

2021-12-07 06:13 UTC, shellyyang1989 commented
/lgtm

2021-12-07 06:20 UTC, shellyyang1989 commented
/label qe-approved

2021-12-08 01:54 UTC, jiajliu commented
/label cherry-pick-approved

2021-12-13 15:37 UTC, LalatenduMohanty commented
/label backport-risk-assessed

2021-12-13 15:39 UTC, merged