Bug 2071998: pkg/cvo/updatepayload: Event when forcing through a sig-verification failure
openshift/cluster-version-operator pull request #763
Opened 2022-04-07 16:38 UTC by wking

For unforced updates, when signature, etc. verification fails, `RetrievePayload` returns an error, and we have emitted events for `RetrievePayload` errors since 475e71f334 (#411).  However, when the user forces the update, we log but do not error out on verification failures.  With this commit, we will also emit a warning event with an error message, which will make it easier to understand how signature verification failed, even [when we don't have access to the logs of the outgoing cluster-version operator][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2071998#c2

2022-04-07 16:58 UTC, LalatenduMohanty approved these changes
/lgtm

2022-04-07 17:20 UTC, LalatenduMohanty commented
/retest

2022-04-08 14:35 UTC, wking commented
Cluster-bot [`test upgrade 4.11.0-0.ci-2022-04-08-015619,openshift/cluster-version-operator#763 4.11.0-0.ci-2022-04-08-015619`][1]:

```
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1512273235499028480/artifacts/launch/gather-extra/artifacts/events.json | jq -r '.items[] | select(.reason == "RetrievePayload") | .metadata.creationTimestamp + " " + .reason + ": " + .message'
...
2022-04-08T04:15:11Z RetrievePayload: Target release version="" image="registry.build01.ci.openshift.org/ci-ln-j2gy3v2/release@sha256:41b7d77d042ad3c4e62d372ea70f6a2b9809e561538fa54b553b93ac5c0c3308" cannot be verified, but continuing anyway because the update was forced: unable to locate a valid signature for one or more sources
```

We'll need a more-specific error out of the verification library, if we're trying to debug slow signature searche.

/hold

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1512273235499028480

2022-04-21 15:42 UTC, LalatenduMohanty requested changes

2022-04-21 15:55 UTC, wking commented on pkg/cvo/sync_worker.go
> +		}
we just want this event for the narrow "update was forced, release was not verified" case.  I didn't think it was worth tying into ClusterVersion reporting.

2022-04-21 21:33 UTC, wking commented
Rebased to pick up openshift/library-go#1358 with cd35f32 -> f05c290.

2022-04-21 23:39 UTC, wking commented
[`test upgrade 4.11.0-0.ci-2022-04-21-074759,openshift/cluster-version-operator#763 4.11.0-0.ci-2022-04-21-074759`][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1517255913856045056/artifacts/launch/gather-extra/artifacts/events.json | jq -r '[.items[] | select(.metadata.namespace == "openshift-cluster-version")] | sort_by(.metadata.creationTimestamp)[] | .metadata.creationTimestamp + " " + .reason + ": " + .message' | grep -1 keyring
2022-04-21T22:15:03Z Completed: Job completed
2022-04-21T22:15:04Z RetrievePayload: Target release version="" image="registry.build01.ci.openshift.org/ci-ln-nt5fbdk/release@sha256:88707bcc9a53ea4eb963b98aee830c1887d5019a664e879b599e030a3bdb142b" cannot be verified, but continuing anyway because the update was forced: unable to verify sha256:88707bcc9a53ea4eb963b98aee830c1887d5019a664e879b599e030a3bdb142b against keyrings: verifier-public-key-redhat
2022-04-21T22:15:04Z LoadPayload: Loading payload version="" image="registry.build01.ci.openshift.org/ci-ln-nt5fbdk/release@sha256:88707bcc9a53ea4eb963b98aee830c1887d5019a664e879b599e030a3bdb142b"
```

Hrm.  So because the event is up in `SyncWorker.syncPayload`, while both verification and the signature check are down in `payloadRetriever.RetrievePayload`, we aren't getting all that much detail on either the timing or the failure mode of the signature check...

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1517255913856045056

2022-05-24 00:03 UTC, wking commented
[test upgrade 4.11.0-0.ci-2022-05-20-165259,openshift/cluster-version-operator#763 4.11.0-0.ci-2022-05-20-165259](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1528827908339011584):

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1528827908339011584/artifacts/launch/gather-extra/artifacts/events.json | jq -r '[.items[] | select(.metadata.namespace == "openshift-cluster-version")] | sort_by(.metadata.creationTimestamp)[] | .metadata.creationTimestamp + " " + .reason + ": " + .message' | grep -1 keyring
2022-05-23T20:41:39Z Completed: Job completed
2022-05-23T20:41:41Z RetrievePayload: Target release version="" image="registry.build01.ci.openshift.org/ci-ln-d3qhbgb/release@sha256:83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76" cannot be verified, but continuing anyway because the update was forced: unable to verify sha256:83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76 against keyrings: verifier-public-key-redhat
2022-05-23T20:41:41Z LoadPayload: Loading payload version="" image="registry.build01.ci.openshift.org/ci-ln-d3qhbgb/release@sha256:83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76"
```

Grr.  Maybe my `Unwrap` dance is broken?

2022-05-24 04:03 UTC, wking commented
[unit][1]:

```
FAIL: TestCVO_UpgradeFailedPayloadLoadWithCapsChanges
...
    cvo_scenarios_test.go:1763: unexpected object:   &v1.ClusterVersion{
          	TypeMeta:   {},
          	ObjectMeta: {Name: "version", ResourceVersion: "3", Generation: 1},
          	Spec:       {ClusterID: "ae71b16e-8325-471a-aa2d-08fdfc5c9925", DesiredUpdate: &{Version: "1.0.0-abc", Image: "image/image:0"}, Channel: "fast", Capabilities: &{BaselineCapabilitySet: "None", AdditionalEnabledCapabilities: {"baremetal", "marketplace"}}, ...},
          	Status: v1.ClusterVersionStatus{
          		... // 3 identical fields
          		VersionHash:  "DL-FFQ2Uem8=",
          		Capabilities: {EnabledCapabilities: {"baremetal", "marketplace"}, KnownCapabilities: {"baremetal", "marketplace", "openshift-samples"}},
          		Conditions: []v1.ClusterOperatorStatusCondition{
          			... // 2 identical elements
          			{Type: "Available", Status: "True", Message: "Done applying 1.0.1-abc"},
          			{Type: "Failing", Status: "False"},
          			{
          				Type:               "Progressing",
        - 				Status:             "True",
        + 				Status:             "False",
          				LastTransitionTime: {},
          				Reason:             "",
        - 				Message:            "Working towards 1.0.1-abc: 3 of 3 done (100% complete)",
        + 				Message:            "Cluster version is 1.0.1-abc",
          			},
          			{Type: "RetrievedUpdates", Status: "False"},
          		},
          		AvailableUpdates:   nil,
          		ConditionalUpdates: nil,
          	},
          }
```

feels unrelated, but see how reproducible it is:

/test unit

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/763/pull-ci-openshift-cluster-version-operator-master-unit/1528937325923405824

2022-05-24 14:40 UTC, wking commented
[test upgrade 4.11.0-0.ci-2022-05-20-165259,openshift/cluster-version-operator#763 4.11.0-0.ci-2022-05-20-165259](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1528972481522569216):

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/release-openshift-origin-installer-launch-gcp-modern/1528972481522569216/artifacts/launch/gather-extra/artifacts/events.json | jq -r '[.items[] | select(.metadata.namespace == "openshift-cluster-version")] | sort_by(.metadata.creationTimestamp)[] | .metadata.creationTimestamp + " " + .reason + ": " + .message' | grep -A2 keyring
Target release version="" image="registry.build01.ci.openshift.org/ci-ln-b7pvh2t/release@sha256:83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76" cannot be verified, but continuing anyway because the update was forced: unable to verify sha256:83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76 against keyrings: verifier-public-key-redhat
[2022-05-24T06:24:57Z: prefix sha256-83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76 in config map signatures-managed: no more signatures to check, 2022-05-24T06:24:57Z: unable to retrieve signature from https://storage.googleapis.com/openshift-release/official/signatures/openshift/release/sha256=83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76/signature-1: no more signatures to check, 2022-05-24T06:24:57Z: unable to retrieve signature from https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release/sha256=83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76/signature-1: no more signatures to check, 2022-05-24T06:24:57Z: parallel signature store wrapping containers/image signature store under https://storage.googleapis.com/openshift-release/official/signatures/openshift/release, containers/image signature store under https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release: no more signatures to check, 2022-05-24T06:24:57Z: serial signature store wrapping config maps in openshift-config-managed with label "release.openshift.io/verification-signatures", parallel signature store wrapping containers/image signature store under https://storage.googleapis.com/openshift-release/official/signatures/openshift/release, containers/image signature store under https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release: no more signatures to check]
2022-05-24T06:25:12Z LoadPayload: Loading payload version="" image="registry.build01.ci.openshift.org/ci-ln-b7pvh2t/release@sha256:83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76"
```

So 5ad3c1434f78's `UpdateError.Unwrap` addition was one of the missing pieces, and we're good now.  Reformatting that error message with more newlines:

* `2022-05-24T06:24:57Z: prefix sha256-83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76 in config map signatures-managed: no more signatures to check` is "no local ConfigMap signatures" (e.g. if the admin had [mirrored a signature in][1]).
* Getting into the parallel store wrapping our two sigstore (HTTP) stores:
    * `2022-05-24T06:24:57Z: unable to retrieve signature from https://storage.googleapis.com/openshift-release/official/signatures/openshift/release/sha256=83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76/signature-1: no more signatures to check`, this is a 404 from Google.
    * `2022-05-24T06:24:57Z: unable to retrieve signature from https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release/sha256=83715487f0af0b6c4efa3e2ab1c506d43a21dd4241108c07fbced05e8b8cfa76/signature-1: no more signatures to check` and a 404 from our mirror.
    * `2022-05-24T06:24:57Z: parallel signature store wrapping containers/image signature store under https://storage.googleapis.com/openshift-release/official/signatures/openshift/release, containers/image signature store under https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release: no more signatures to check` and the parallel store that wraps the two sigstore (HTTP) stores runs out of options.
* `2022-05-24T06:24:57Z: serial signature store wrapping config maps in openshift-config-managed with label "release.openshift.io/verification-signatures", parallel signature store wrapping containers/image signature store under https://storage.googleapis.com/openshift-release/official/signatures/openshift/release, containers/image signature store under https://mirror.openshift.com/pub/openshift-v4/signatures/openshift/release: no more signatures to check` and the serial store that wraps the ConfigMap and parallel stores runs out of options.

Looks good to me.

[1]: https://docs.openshift.com/container-platform/4.10/updating/updating-restricted-network-cluster.html#update-mirror-repository_updating-restricted-network-cluster

2022-05-24 18:46 UTC, jottofar commented
/lgtm
/retest

2022-05-24 21:22 UTC, wking commented
/hold cancel

Error message is [more specific][1] now.

[1]: https://github.com/openshift/cluster-version-operator/pull/763#issuecomment-1136018046

2022-05-24 21:23 UTC, wking commented
[`Watchdog` gaps][1] are unrelated.

/override ci/prow/e2e-agnostic-upgrade

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/763/pull-ci-openshift-cluster-version-operator-master-e2e-agnostic-upgrade/1528972375691890688

2022-05-24 21:26 UTC, merged