syncStatus: Reduce verbosity when syncing nothing of interest
openshift/cluster-version-operator pull request #922
Opened 2023-04-05 09:25 UTC by petr-muller

Status is synchronized every 15 seconds, and each call is currently logged with a lot of metadata, including full `status`. The metadata include words `error` and `Failure` which usually have zero values, but the words get noticed by filters and people eyeballing the logs:

```
I0405 09:24:26.084143       1 status.go:170] Synchronizing status errs=field.ErrorList(nil) status=&cvo.SyncWorkerStatus{Generation:55, Failure:error(nil), Done:830, Total:830, Completed:107, Reconciling:true, Initial:false, VersionHash:"yroEV7BhWJo=", Architecture:"amd64", LastProgress:time.Date(2023, time.April, 5, 9, 21, 50, 486422587, time.Local), Actual:v1.Release{Version:"4.12.10", Image:"quay.io/openshift-release-dev/ocp-release@sha256:db976910d909373b1136261a5479ed18ec08c93971285ff760ce75c6217d3943", URL:"https://access.redhat.com/errata/RHBA-2023:1508", Channels:[]string(nil)}, Verified:false, loadPayloadStatus:cvo.LoadPayloadStatus{Step:"PayloadLoaded", Message:"Payload loaded version=\"4.12.10\" image=\"quay.io/openshift-release-dev/ocp-release@sha256:db976910d909373b1136261a5479ed18ec08c93971285ff760ce75c6217d3943\" architecture=\"amd64\"", AcceptedRisks:"", Failure:error(nil), Update:v1.Update{Version:"4.12.10", Image:"quay.io/openshift-release-dev/ocp-release@sha256:db976910d909373b1136261a5479ed18ec08c93971285ff760ce75c6217d3943", Force:false}, Verified:false, Local:true, LastTransitionTime:time.Time{wall:0xc102c34e44dd634f, ext:2230452990, loc:(*time.Location)(0x2f4afa0)}}, CapabilitiesStatus:cvo.CapabilityStatus{Status:v1.ClusterVersionCapabilitiesStatus{EnabledCapabilities:[]v1.ClusterVersionCapability{"CSISnapshot", "Console", "Insights", "Storage", "baremetal", "marketplace", "openshift-samples"}, KnownCapabilities:[]v1.ClusterVersionCapability{"CSISnapshot", "Console", "Insights", "Storage", "baremetal", "marketplace", "openshift-samples"}}, ImplicitlyEnabledCaps:[]v1.ClusterVersionCapability(nil)}}
```

Because most of the time this event is not interesting, we can only log it if we happen to sync something interesting, like a failure, an only log every event on higher verbosity.

2023-04-05 14:14 UTC, LalatenduMohanty requested changes

2023-04-05 14:14 UTC, LalatenduMohanty commented on pkg/cvo/status.go
> +	infoVerbosity := klog.Level(4)
Nitpick, a variable name as `verbosityLevel` would be easy to understand than infoVerbosity. But if you feel strongly about the current name then I can still add lgtm.

2023-04-05 14:54 UTC, petr-muller commented
/test e2e-agnostic-ovn-upgrade-out-of-change

looks like infra hiccup, who wrote that CI? :trollface:

2023-04-06 09:12 UTC, petr-muller commented
So the failure makes me a little jumpy in context of #920 but we [discussed](https://redhat-internal.slack.com/archives/CEKNRGF25/p1680719467763049?thread_ts=1679676028.875809&cid=CEKNRGF25) that on Slack and apparently this is a different problem and the fix is the revert in https://github.com/openshift/operator-framework-olm/pull/478 

Also, I have [verified via search.ci](https://search.ci.openshift.org/?search=https%3A%2F%2Fthanos-querier-openshift-monitoring.*api%2Fv1%2Fquery.*i%2Fo+timeout&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job) that *our* failure did not start with #920 but it started earlier.

2023-04-06 10:51 UTC, petr-muller commented
/test e2e-agnostic-ovn-upgrade-into-change

Installation failed, apiserver failed to go up

2023-04-06 14:21 UTC, petr-muller commented
/override ci/prow/e2e-agnostic-ovn-upgrade-into-change

Nothing I have seen is related to a logging change ;)

2023-04-06 14:32 UTC, merged